---- You can use this file to load seed data into the database using SQL statements
--insert into Member (id, name, email, phone_number) values (1, 'John Smith', 'john.smith@mailinator.com', '2125551212')
--insert into role (id,role) values (1,'USER')
insert into suitetype values (1,'Single')
insert into suitetype values (2,'Single+Extra')
insert into suitetype values (3,'Double')
insert into suitetype values (4,'Double+Extra')
--
insert into facility values (1,'TV')
insert into facility values (2,'A/C')
insert into facility values (3,'FAN')
insert into facility values (4,'LOCKER')
insert into facility values (5,'FREE NEWS PAPER')
insert into facility values (6,'FRIDGE')
insert into facility values (7,'WASHING MACHINE')
insert into facility values (8,'WIFI')
insert into facility values (9,'MICROWAVE')
insert into facility values (10,'TRAVEL DESK')
insert into facility values (11,'PICK UP AND DROP')
insert into facility values (12,'CAR RENTAL DESK')