package com.indi.stay.domain;

// Generated 13 Jun, 2014 7:51:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facility generated by hbm2java
 */
@Entity
//@Table(name = "facility", catalog = "stay001")
public class Facility implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String equipment;
	private Set<StaySuite> staySuites = new HashSet<StaySuite>(0);

	public Facility() {
	}

	public Facility(int id, String equipment) {
		this.id = id;
		this.equipment = equipment;
	}

	@Id
	@Column(name = "facility_id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "equipment", nullable = false, length = 50)
	public String getEquipment() {
		return this.equipment;
	}

	public void setEquipment(String equipment) {
		this.equipment = equipment;
	}
	
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "stay_suite_facility", joinColumns = { 
			@JoinColumn(name = "facility_id", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "staysuite_id", 
					nullable = false, updatable = false) })
	public Set<StaySuite> getStaySuites() {
		return staySuites;
	}

	public void setStaySuites(Set<StaySuite> staySuites) {
		this.staySuites = staySuites;
	}
	
	

}
