package com.indi.stay.domain;

// Generated 29 Jun, 2014 2:35:14 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * StayBookingDetails generated by hbm2java
 */
@Entity
//@Table(name = "stay_booking_details", catalog = "stay001")
public class StayBookingDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private StaySuite staysuite;
	private Date fromDate;
	private Date toDate;

	public StayBookingDetails() {
	}

	public StayBookingDetails(int id) {
		this.id = id;
	}

	public StayBookingDetails(int id, StaySuite staysuite, Date fromDate,
			Date toDate) {
		this.id = id;
		this.staysuite = staysuite;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staysuite_id")
	public StaySuite getStaysuite() {
		return this.staysuite;
	}

	public void setStaysuite(StaySuite staysuite) {
		this.staysuite = staysuite;
	}

	@Column(name = "from_date")
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Column(name = "to_date")
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
