package com.indi.stay.domain;

// Generated 29 Jun, 2014 2:35:14 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Staymenu generated by hbm2java
 */
@Entity
//@Table(name = "staymenu", catalog = "stay001")
public class StayMenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Stay stay;
	private String menuphoto;

	public StayMenu() {
	}

	public StayMenu(int id, Stay stay, String menuphoto) {
		this.id = id;
		this.stay = stay;
		this.menuphoto = menuphoto;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stay_id", nullable = false)
	public Stay getStay() {
		return this.stay;
	}

	public void setStay(Stay stay) {
		this.stay = stay;
	}

	@Column(name = "menuphoto", nullable = false, length = 200)
	public String getMenuphoto() {
		return this.menuphoto;
	}

	public void setMenuphoto(String menuphoto) {
		this.menuphoto = menuphoto;
	}

}
