package com.indi.stay.domain;

// Generated 13 Jun, 2014 7:51:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

/**
 * Stay generated by hbm2java
 */
@Entity
//@Table(name = "stay", catalog = "stay001")
public class Stay implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;

	@NotNull
	@Size(min = 1, max = 25)
	@Pattern(regexp = "[A-Za-z ]*", message = "must contain only letters and spaces")

	private String stayname;

	@NotNull
	@Size(min = 1, max = 25)
	@Pattern(regexp = "[A-Za-z ]*", message = "must contain only letters and spaces")

	private String address;

	@NotNull
	@Size(min = 10, max = 12)
	@Digits(fraction = 0, integer = 12)
	private String phoneno;

	@NotNull
	@NotEmpty
	@Email
	private String emailid;
	
	private CommonsMultipartFile profileImagePic;
	
	private String profileImgPath; 
	
	private String websitelink;
	private Integer rating;
	private Set<StaySuite> staySuites = new HashSet<StaySuite>(0);
	private Set<StayNearbyPlaces> stayNearbyPlaceses = new HashSet<StayNearbyPlaces>(0);
	private Set<StayPhotos> stayPhotoses = new HashSet<StayPhotos>(0);
	private Set<StayMenu> staymenus = new HashSet<StayMenu>(0);

	public Stay() {
	}

	public Stay(int id, String stayname, String address, String phoneno,
			String emailid, String websitelink) {
		this.id = id;
		this.stayname = stayname;
		this.address = address;
		this.phoneno = phoneno;
		this.emailid = emailid;
		this.websitelink = websitelink;
	}

	public Stay(int id, String stayname, String address, String phoneno,
			String emailid, String websitelink, Set<StaySuite> staySuites,
			Set<StayNearbyPlaces> stayNearbyPlaceses, Set<StayPhotos> stayPhotoses,Integer rating, Set<StayMenu> staymenus) {
		this.id = id;
		this.stayname = stayname;
		this.address = address;
		this.phoneno = phoneno;
		this.emailid = emailid;
		this.websitelink = websitelink;
		this.staySuites = staySuites;
		this.stayNearbyPlaceses = stayNearbyPlaceses;
		this.stayPhotoses = stayPhotoses;
		this.staymenus = staymenus;
		this.rating = rating;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "stayname", nullable = false, length = 50)
	public String getStayname() {
		return this.stayname;
	}

	public void setStayname(String stayname) {
		this.stayname = stayname;
	}

	@Column(name = "address", nullable = false, length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneno", nullable = false, length = 12)
	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	@Column(name = "emailid", nullable = false, length = 50)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "websitelink", nullable = false, length = 50)
	public String getWebsitelink() {
		return this.websitelink;
	}

	public void setWebsitelink(String websitelink) {
		this.websitelink = websitelink;
	}

	@Column(name = "profileImagePic", nullable = true,columnDefinition="LONGBLOB")
	public CommonsMultipartFile getProfileImagePic() {
		return profileImagePic;
	}

	public void setProfileImagePic(CommonsMultipartFile profileImagePic) {
		this.profileImagePic = profileImagePic;
	}

	@Column(name = "profileImgPath", nullable = true)
	public String getProfileImgPath() {
		return profileImgPath;
	}

	public void setProfileImgPath(String profileImgPath) {
		this.profileImgPath = profileImgPath;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stay")
	public Set<StaySuite> getStaySuites() {
		return staySuites;
	}

	public void setStaySuites(Set<StaySuite> staySuites) {
		this.staySuites = staySuites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stay")
	public Set<StayNearbyPlaces> getStayNearbyPlaceses() {
		return stayNearbyPlaceses;
	}

	public void setStayNearbyPlaceses(Set<StayNearbyPlaces> stayNearbyPlaceses) {
		this.stayNearbyPlaceses = stayNearbyPlaceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stay")
	public Set<StayPhotos> getStayPhotoses() {
		return stayPhotoses;
	}

	public void setStayPhotoses(Set<StayPhotos> stayPhotoses) {
		this.stayPhotoses = stayPhotoses;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stay")
	public Set<StayMenu> getStaymenus() {
		return this.staymenus;
	}

	public void setStaymenus(Set<StayMenu> staymenus) {
		this.staymenus = staymenus;
	}

}
